### ISSUE TITLE
Suggestions for Getting Started Page

### ISSUE THREAD

**Issue by TristanHodgins** [byu-cpe/ecen224#84] opened 2024-05-01 16:32 UTC
"Once the extension has successfully installed, you can now click on the **green** icon in the bottom left corner as seen in the figure above."

The color is dependant on the theme.  With the default theme (Dark Modern), this button is blue.

**Comment by philipbl** [comment] 2024-09-16 14:49
Duplicate of #86.

**Closed by philipbl** 2024-09-16 14:49 UTC
